"""
Verifier agent interface and deterministic mock implementation for MARS.
"""

from __future__ import annotations

import abc

from app.models import ProposedPlan, VerificationResult, WorldState


class BaseVerifier(abc.ABC):
    """Abstract base interface for all Verifier agents."""

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Human-readable name of the verifier."""

    @abc.abstractmethod
    async def verify(
        self,
        world_state: WorldState,
        proposed_plan: ProposedPlan,
    ) -> VerificationResult:
        """
        Verify a proposed plan against world state, objective, and safety constraints.

        Args:
            world_state: Current point-in-time state snapshot.
            proposed_plan: Proposed plan generated by the planner.

        Returns:
            Structured VerificationResult.
        """


class MockVerifier(BaseVerifier):
    """
    Deterministic rule-based verifier inspecting structural validity and safety constraints.

    Verifies:
      - Objective consistency & required non-empty fields
      - Step ordering and non-empty steps list
      - Restricted actions against WorldState.restrictions
      - Duplicate / invalid actions
    """

    @property
    def name(self) -> str:
        return "MockVerifierAgent-v1"

    async def verify(
        self,
        world_state: WorldState,
        proposed_plan: ProposedPlan,
    ) -> VerificationResult:
        """Run independent verification checks on proposed_plan."""
        issues: list[str] = []
        warnings: list[str] = []
        checked_restrictions = list(world_state.restrictions)

        # 1. Structural check: non-empty plan
        if not proposed_plan.steps:
            issues.append("Proposed plan contains no steps.")

        # 2. Objective check
        if not proposed_plan.objective:
            warnings.append("Proposed plan objective is empty.")

        # 3. Step validation & restriction check
        seen_tools: set[str] = set()
        for step in proposed_plan.steps:
            # Required fields
            if not step.tool or not step.description:
                issues.append(f"Step '{step.step_number}' has missing tool or description.")

            # Restricted action check
            if step.tool in world_state.restrictions:
                issues.append(
                    f"Step '{step.step_number}' invokes prohibited tool '{step.tool}' listed in restrictions."
                )

            # Explicit prohibition mock test check
            if step.tool == "prohibited_action" or step.tool == "restricted_tool":
                issues.append(f"Step '{step.step_number}' invokes prohibited tool '{step.tool}'.")

            # Duplicate step check
            if step.tool in seen_tools:
                warnings.append(f"Duplicate invocation of tool '{step.tool}' detected.")
            else:
                seen_tools.add(step.tool)

        approved = len(issues) == 0
        risk_level = "low"
        if not approved:
            risk_level = "high"
        elif warnings:
            risk_level = "medium"

        return VerificationResult(
            approved=approved,
            risk_level=risk_level,
            issues=issues,
            warnings=warnings,
            checked_restrictions=checked_restrictions,
            verifier_version=self.name,
        )
